project:
  type: website
  output-dir: docs

website:
  title: "cmarverse"
  favicon: "figures/cmar3.png"
  navbar:
    logo: "figures/cmar3.png"
    left:
      - href: cmarverse.qmd
        text: Overview
      - style_guide.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



