project:
  type: website
  output-dir: docs

website:
  title: "cmarverse"
  navbar:
    left:
      - href: cmarverse.qmd
        text: Overview
      - style_guide.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



